# Turbine Documentation - Zola Configuration
base_url = "https://tschoffelen.github.io/turbine"
title = "Turbine"
description = "Type-safe entity mapping and query library for DynamoDB"
compile_sass = false
build_search_index = false
generate_feeds = false

[markdown]
highlight_code = true
highlight_theme = "two-dark"

[extra]
